### ISSUE TITLE
H265 HEVC video not playing on unsupported device

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#51]
I check H265 HEVC video not playing on unsupported device. but that perfectly work on vlc player even low end phone not supported h265 codecs.

```
E/ExoPlayerImplInternal( 5273): Playback error
E/ExoPlayerImplInternal( 5273):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/hevc, hvc1.2.4.L93.90, 386059, null, [1280, 720, 23.976], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
E/ExoPlayerImplInternal( 5273):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5273):       at android.os.Looper.loopOnce(Looper.java:205)
E/ExoPlayerImplInternal( 5273):       at android.os.Looper.loop(Looper.java:294)
E/ExoPlayerImplInternal( 5273):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5273):   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.goldfish.hevc.decoder
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1642)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:805)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1015)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:510)
E/ExoPlayerImplInternal( 5273):       ... 4 more
E/ExoPlayerImplInternal( 5273):   Caused by: android.media.MediaCodec$CodecException: Error 0xe
E/MediaCodec( 5273): flush() is valid only at Executing states; currently at Released state
E/ExoPlayerImplInternal( 5273): Disable failed.
E/ExoPlayerImplInternal( 5273):   java.lang.IllegalStateException: flush() is valid only at Executing states; currently at Released state
E/ExoPlayerImplInternal( 5273):   
E/ExoPlayerImplInternal( 5273):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal( 5273):       at android.media.MediaCodec.flush(MediaCodec.java:2504)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:230)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:869)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:862)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:702)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:612)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:190)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1679)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1420)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1381)
E/ExoPlayerImplInternal( 5273):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:602)
E/ExoPlayerImplInternal( 5273):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5273):       at android.os.Looper.loopOnce(Looper.java:205)
E/ExoPlayerImplInternal( 5273):       at android.os.Looper.loop(Looper.java:294)
E/ExoPlayerImplInternal( 5273):       at android.os.HandlerThread.run(HandlerThread.java:67)
D/MediaCodec( 5273): keep callback message for reclaim
I/CCodecConfig( 5273): query failed after returning 20 values (BAD_INDEX)
D/CCodecConfig( 5273): c2 config diff is   c2::u32 raw.channel-mask.value = 12
D/CCodecConfig( 5273):   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client( 5273): query -- param skipped: index = 1342179345.
W/Codec2Client( 5273): query -- param skipped: index = 2415921170.
W/Codec2Client( 5273): query -- param skipped: index = 1610614798.
D/PipelineWatcher( 5273): onInputBufferReleased: frameIndex not found (2); ignored
D/CCodecBufferChannel( 5273): [c2.android.aac.decoder#782] Ignoring stale input buffer done callback: last flush index = 4, frameIndex = 2
D/PipelineWatcher( 5273): onInputBufferReleased: frameIndex not found (3); ignored
D/CCodecBufferChannel( 5273): [c2.goldfish.hevc.decoder#429] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5273): [c2.android.aac.decoder#782] Ignoring stale input buffer done callback: last flush index = 4, frameIndex = 3
D/PipelineWatcher( 5273): onInputBufferReleased: frameIndex not found (3); ignored
D/CCodecBufferChannel( 5273): [c2.goldfish.hevc.decoder#429] MediaCodec discarded an unknown buffer
cancelBuffer: BufferQueue has no connected producer
I/hw-BpHwBinder( 5273): onLastStrongRef automatically unlinking death recipients
D/MediaCodec( 5273): flushMediametrics
D/CCodecBufferChannel( 5273): [c2.android.aac.decoder#782] MediaCodec discarded an unknown buffer
D/MediaCodec( 5273): flushMediametrics
W/MediaCodec( 5273): no metrics handle found
D/CCodecBufferChannel( 5273): [c2.android.aac.decoder#782] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5273): [c2.android.aac.decoder#782] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5273): [c2.android.aac.decoder#782] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 5273): onLastStrongRef automatically unlinking death recipients
D/MediaCodec( 5273): flushMediametrics
D/MediaCodec( 5273): flushMediametrics
W/MediaCodec( 5273): no metrics handle found
D/bccm    ( 5273): playbackState: 1
```

**Comment by sudhanshugairola** [comment]
https://medium.com/@juegeorge/exoplayer-enabling-low-end-device-playback-7656aded13fc

**Comment by sudhanshugairola** [comment]
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg

**Comment by sudhanshugairola** [comment]
fixed by my self

**Comment by andreasgangso** [comment]
I @sudhanshugairola It would be interesting to know how you solved this! :)

**Comment by sudhanshugairola** [comment]
by using codecs extention.

**Comment by andreasgangso** [comment]
> by using codecs extensions.

this? https://github.com/michalliu/exoplayer2-hevc-extension

**Comment by sudhanshugairola** [comment]
that only for hevc and not working well. https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg

**Comment by sudhanshugairola** [comment]
[bccm-player-main.zip](https://github.com/bcc-code/bccm-player/files/13295001/bccm-player-main.zip)

better if you will try modified bccm source code

**Comment by andreasgangso** [comment]
> [bccm-player-main.zip](https://github.com/bcc-code/bccm-player/files/13295001/bccm-player-main.zip)
> 
> better if you will try modified bccm source code
> 
> which i modified that support all codecs except dolby vision. Audio: Vorbis, Opus, Flac, Alac, pcm_mulaw, pcm_alaw, MP3, Amrnb, Amrwb, AAC, AC3, EAC3, dca, mlp, truehd Video: H.264, HEVC, VP8, VP9**
> 
> Most of Android TV or android box does not have vast codecs supported that why codecs issue will appear while playing video

It would be cool if you look up how to fork and make a PR to the repo so that I can include it 👍

**Comment by sudhanshugairola** [comment]
Okay but that took so much time to match with original bccm code

**Comment by andreasgangso** [comment]
> Okay but that took so much time to match with original bccm code

Ok. Anyway I'm thankful for the zip you sent.
The only important changes I see is the following:

ExoPlayerController.kt

<img width="938" alt="image" src="https://github.com/bcc-code/bccm-player/assets/727125/adc652d0-e991-446a-8cbb-b363f759fb5c">


build.gradle

<img width="817" alt="image" src="https://github.com/bcc-code/bccm-player/assets/727125/fe857ff7-21ae-44cd-9d29-5c4d55ebc583">

Is that correct?

**Comment by sudhanshugairola** [comment]
Yes right that's only.
