### ISSUE TITLE
Mp4 and mkv download issue

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#55]
Try to download MP4 and mkv that's create issue because of tracks, Need some fix.
https://github.com/androidx/media/issues/289

**Comment by andreasgangso** [comment]
Need more details here

**Comment by sudhanshugairola** [comment]
E/flutter (14758): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.IllegalStateException, IllegalStateException, Cause: null, Stacktrace: java.lang.IllegalStateException
E/flutter (14758): 	at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
E/flutter (14758): 	at androidx.media3.exoplayer.offline.DownloadHelper.assertPreparedWithMedia(DownloadHelper.java:897)
E/flutter (14758): 	at androidx.media3.exoplayer.offline.DownloadHelper.getTracks(DownloadHelper.java:560)
E/flutter (14758): 	at media.bcc.bccm_player.Downloader.startDownload(Downloader.kt:201)
E/flutter (14758): 	at media.bcc.bccm_player.Downloader$startDownload$1.invokeSuspend(Unknown Source:15)
E/flutter (14758): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/flutter (14758): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/flutter (14758): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter (14758): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (14758): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter (14758): 	at android.os.Looper.loop(Looper.java:294)
E/flutter (14758): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/flutter (14758): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14758): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter (14758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter (14758): , null)
E/flutter (14758): #0      DownloaderPigeon.startDownload (package:bccm_player/src/pigeon/downloader_pigeon.g.dart:236:7)
E/flutter (14758): <asynchronous suspension>
E/flutter (14758): #1      DownloaderNative.startDownload (package:bccm_player/src/downloader_platform_interface.dart:44:12)
E/flutter (14758): <asynchronous suspension>
E/flutter (14758): #2      _DownloaderState.build.<anonymous closure>.<anonymous closure> (package:bccm_player_example/examples/downloader.dart:135:40)
E/flutter (14758): <asynchronous suspension>
E/flutter (14758): 
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
D/EGL_emulation(14758): app_time_stats: avg=3234.30ms min=5.01ms max=31443.91ms count=10
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
W/MediaRouter(14758): Ignoring invalid provider descriptor: null
D/CompatibilityChangeReporter(14758): Compat change id reported: 78294732; UID 10191; state: ENABLED
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
D/EGL_emulation(14758): app_time_stats: avg=492.43ms min=8.25ms max=2352.36ms count=5
D/EGL_emulation(14758): app_time_stats: avg=183.65ms min=1.35ms max=2185.82ms count=14
D/EGL_emulation(14758): app_time_stats: avg=116.40ms min=2.50ms max=2210.43ms count=23
D/EGL_emulation(14758): app_time_stats: avg=116.62ms min=2.58ms max=2218.85ms count=23
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
E/FrameEvents(14758): updateAcquireFence: Did not find frame.
E/FrameEvents(14758): updateAcquireFence: Did not find frame.

**Comment by sudhanshugairola** [comment]
any update
